### ISSUE TITLE
SpellArray causes server crash if out of bounds

### ISSUE THREAD

**Issue by GoldenretriverYT** [GOOMBAServer/GOOMBAServer-src#9]
**Describe the bug**
Title

**To Reproduce**
Use this code:
```
->GOOMBATIME<-
ARRAYADD: MyCoolArray
SPELLARRAY: MyCoolArray 0
```

**Expected behavior**
Should not crash server

**Comment by GoldenretriverYT** [comment]
is this project dead?

**Comment by GoombaProgrammer** [comment]
yes it is

**Comment by GoldenretriverYT** [comment]
BUT U PROMISED IT ISNT DEAD IN README.md

**Comment by GoombaProgrammer** [comment]
i am working on too many projects maybe soon

**Comment by GoldenretriverYT** [comment]
still not fixed :angery:
